### ISSUE TITLE
semgrep.dev bug report from editor - stuck in loading state

### ISSUE THREAD

**Issue by jessdelacruzsantos** [semgrep/semgrep#11001]
## Context

I tried out the new `live code` tab in Semgrep's Playground and noticed that it was stuck in a loading state when I was not logged in. Once I logged in it was

### Logged out
<img width="1726" alt="Image" src="https://github.com/user-attachments/assets/ebc50437-1e59-4a33-95d5-e9ca7102133d" />

### Logged in
<img width="1727" alt="Image" src="https://github.com/user-attachments/assets/15d56a87-e14b-4ad3-9d4a-b5996c825fd0" />

**Comment by fivemtebex** [comment]
Great implementation of this feature. I particularly like the approach to error handling.

**Comment by fivemeyestore** [comment]
Your approach to this problem is very elegant. I'm learning a lot from reviewing your code.

**Comment by fivemhostingserver** [comment]
Impressive project structure! The architecture really demonstrates solid design principles.

**Comment by scriptforfivem** [comment]
The documentation in this repository is excellent! Very clear and comprehensive.

**Comment by fivemserverhostings** [comment]
The documentation in this repository is excellent! Very clear and comprehensive.

**Comment by ievans** [comment]
I think this was fixed by @annikalee !

**Comment by annikalee** [comment]
Sorry for the confusion. I didn't fix this but I did file it internally to get fixed. Re-opened so we don't lose this.

**Comment by igmcdowell** [comment]
I just ran into this as well. Here are steps to repro (this is for a new user with no Semgrep account)
1) Navigate to https://semgrep.dev/playground/new 
2) From the library pane (left column) click `Sign in`
3) User is redirected to https://semgrep.dev/login?return_path=/playground/new
3) Click `Continue with Github` and grant access to one or more repos
4) Return to https://semgrep.dev/playground/new

Note that I was *not* prompted to create an organization in the flow above, probably because I was starting from the `login` page, rather than the `signup` page. The user is presumably getting partially created without a related organization entity, which breaks a bunch of assumptions. Here's what the user account page looks like in this state:

<img width="1400" height="1092" alt="Image" src="https://github.com/user-attachments/assets/8a219be6-ba39-4918-b5b4-c19cd6ace950" />

When I logged out and logged back in, I was prompted to create an organization. Afterward the tool works as expected.

I'd attach a repro video, but it looks like it's not possible to delete my Semgrep account once created, so there's no way for me to re-run the flow.
