### ISSUE TITLE
Metavariable for method call should be matched against corresponding metavariable in method definition

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#1861]
@msorens to looking to have https://semgrep.dev/s/erDl match as part of a more complex pattern. I triaged it down to a difference between `this.checkTypeChange()` and `checkTypeChange()` not being the same so `$FUNC` isn't matching both as perhaps it should. I also couldn't get `this.$FUNC` to match in the pattern https://semgrep.dev/s/vZ44

**Comment by DrewDennison** [comment]
More details in https://r2c-community.slack.com/archives/CK86BJ5DW/p1603248889264700

**Comment by aryx** [comment]
Your second solution, with this.$FUNC should now work.

**Comment by msorens** [comment]
Just tested the "second solution" above (https://semgrep.dev/s/vZ44) and the behavior is unchanged with 0.29.0; still not matching.

**Comment by aryx** [comment]
it works on develop.
https://semgrep.dev/s/vZ44?version=develop

it should be in the next release (0.30).

**Comment by msorens** [comment]
Yes, I see it does work on "develop" per the link above, but it is not working on the released 0.30.0--even though it is in the release notes for 0.30.0. Perhaps it was not actually included in the release?

**Comment by chmccreery** [comment]
@msorens it looks like semgrep.dev accidentally did not get updated to use 0.30.0 yet - should be done later today I think!

**Comment by chmccreery** [comment]
Ok, 0.30 has been deployed on semgrep.dev and it looks like [https://semgrep.dev/s/vZ44](https://semgrep.dev/s/vZ44) now works. Sorry for the release delay, and thanks for pointing it out

**Comment by msorens** [comment]
I had first seen this--or so I thought(!)--when running locally. Turns out it was my error--my real pattern had a flaw. So, yes, this is good as is!
