### ISSUE TITLE
[Java] Add the ability to use ellipsis (or equivalent) for method chaining.

### ISSUE THREAD

**Issue by j-martin** [semgrep/semgrep#2208]
**Is your feature request related to a problem? Please describe.**

The ellipsis `...` operator does not seem to support usage in method chaining. https://semgrep.dev/docs/writing-rules/pattern-syntax/#ellipsis-operator

For example, we want to ensure a fluent API / builder-like (from an external library) is invoked in the right order. We do not care about any method calls in between. More specifically, we use jOOQ which can leak DB connections if `.stream()`  is invoked without a prior `.fetch`.

In the case below `...` denotes that any number of other method calls may be done before building the query.

```java
// Bad, may leak connections
db.selectFrom()...
  .stream()
  ...

// Better
db.selectFrom()...
  .fetch()
  .stream()
  ...
```

I could imagine writing a rule to check for JS/TS to ensure `Future` invoke/define `.catch(...)` or something like that.

**Describe the solution you'd like**
The `...` operator or an equivalent wild-card that supports ignoring interstitial method calls or subsequent method calls. I am thinking we may want something else than `...` or a way to escape it as `db....stream()` ends up being a lot of periods.

**Describe alternatives you've considered**
Maybe a regex, but that may defeat the purpose of using `semgrep`.

**Additional context**

https://r2c-community.slack.com/archives/C018NJRRCJ0/p1607366986093500

**Comment by aryx** [comment]
Good idea, given those method chains emulate are similar to sequence of statements.

**Comment by aryx** [comment]
I would vote for
x.foo(). ... .bar(). ...

**Comment by aryx** [comment]
I am a bit worried about grammar ambiguity with x.foo()...bar()... but maybe it is possible

**Comment by nbrahms** [comment]
@aryx my vote would be for `x.$...METHODS.bar()` FWIW.

**Comment by nbrahms** [comment]
An interesting suggestion might be to adopt:

`${[...]VAR} | $[...]VAR | ${...} | ...`

as a complete generic syntax for wildcard matching, with the first option the preferred unambiguous syntax. This would allow users to unambiguously describe method chaining, for instance.

The downside is that you'd conflict with interpolation dialects in JavaScript and Scala.

To match method chaining, then, one could just write:

```java
target.${...}.method(...).${...};
```

**Comment by aryx** [comment]
Ok, let's try the syntax @j-martin intuitively used: x.foo()... .bar()...
this seems to not generate any grammar conflicts. When written on a single line it's a bit ugly, but on multi-line, as method
chaining is usually used, it's not bad:
```
db.selectFrom()
   ...
  .fetch()
  .stream()
  ...
```
it's actually pretty similar to what we have for statements
db.selectFrom();
...
fetch();
stream();
...

**Comment by underyx** [comment]
`x.foo()...().bar()`

is another one to consider just cause it looks more like actual method chaining

**Comment by j-martin** [comment]
Unless I am mistaken, @underyx `...()` would infer that the method has a zero-arity. `...(...)` would be more correct, but not necessarily describe really that it is an arbitrary number of the method calls. 

@aryx I think `db.selectFrom() ... .fetch().stream()` is reasonable as long the doc insists on the importance of the spaces or new lines. Would `db.selectFrom()... .fetch().stream()` still be valid? Mais bon, vous savez plus moi. ;)

**Comment by aryx** [comment]
Je pense que je vais suivre ton intuition d'origine. $O.foo() ... .bar() ... me parait une bonne idee.

Note that you may have to write them on a single line in the pattern because of the way ASI (Automatic semicolon insertion)
does not always play well with the few semgrep extensions to the Javascript grammar.

**Comment by j-martin** [comment]
@aryx can we re-open this issue to add Java support or should I create a new issue? [jOOQ](https://www.jooq.org/) is a Java library. I was not clear about which language I was looking for. I did mention JS/TS since we use TS for our front-end.

**Comment by aryx** [comment]
Should work now for Java.

**Comment by j-martin** [comment]
@aryx I gave 0.35 a try and java still does not work. Looking at the git log it should have made it in the [release](https://github.com/returntocorp/semgrep/commits/1f5c79ceea37d6679ad3bd6c8549de199f557020). 

JS: Works
```
$ semgrep -e 'db....stream()' -l js .
ran 1 rules on 0 files: 0 findings
```

Java: Does not work
```
$ semgrep -e 'db....stream()' -l java .
semgrep error: invalid pattern
  --> CLI Input:1
1 | db....stream()
  | ^^^^^^
```

```
semgrep --version
0.35.0
```

**Comment by aryx** [comment]
weird, this....stream() works, but not db....stream(). I also get a parse error in that last case.

**Comment by aryx** [comment]
Actually we probably need to revert the support for method chaining using '...' for Javascript. It introduces some regressions
for other rules: https://github.com/returntocorp/semgrep-rules/issues/1055

**Comment by aryx** [comment]
So I'll go with my original proposal and require an extra ".", so $O.foo() . ... .bar(). ...
A bit heavy, but does not generate problems with ASI and avoid ambiguity with patterns like
```
$O.foo()
...
```
which we want to be considered statements (and where we insert extra semicolon after $O.foo(); like Javascript does).

**Comment by aryx** [comment]
So both method chaining in Java and JS now requires an extra ".", so:
```
$O
 . ...
 .foo()
 . ...
 .bar()
```
to look for method calls with bar called after foo on any object.

**Comment by aryx** [comment]
and you need the extra space between '.' and '...'
(I could fix it with lexing hack if it really bothers you).

**Comment by j-martin** [comment]
I think the morse code approach is perfectly reasonable and less ambiguous.

Thanks!

**Comment by aryx** [comment]
Ahah i like the morse reference.

**Comment by j-martin** [comment]
@aryx just to confirm semgrep 0.37 works as intended. Merci beaucoup!

**Comment by aryx** [comment]
Parfait!
