### ISSUE TITLE
Autofix overwrites wrong line with multiple multiline matches

### ISSUE THREAD

**Issue by JuliusDegesys** [semgrep/semgrep#3388]
**Describe the bug**
Incorrect chunks of the file are auto-fixed. Searching for `assert_eq(True, $X)` and replacing with `assert $X` will mangle the output when auto-fixing multiple multi-line matches.

**To Reproduce**
https://semgrep.dev/s/juliusdegesys:asserteqbug
Input file:
```python
assert_eq(
    True, "a"
)
assert_eq(
    True, "b"
)
x = "abc"
```
Rule:
```yaml
rules:
    - id: assert_eq-true
      message: Change assert_eq(True, x) to assert x
      severity: INFO
      languages:
      - python
      pattern: assert_eq(True, $ACTUAL)
      fix: assert $ACTUAL
```
The matches look correct, and so do the auto-fixes. But when you "Apply all fixes" or apply the first fix followed by the second, the following output is generated:
```python
assert "a"
assert_eq(
    True, "b"
assert "b"
```

**Expected behavior**
```python
assert "a"
assert "b"
x = "abc"
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
```
pip install semgrep
$ semgrep --version
0.56.0
```

**Comment by colleend** [comment]
Hi! Thanks for filing this issue -- we'll look into it as soon as we get the time to. As a heads up, autofix is an alpha feature so it is not as well supported as other GA features!

**Comment by gordonwoodhull** [comment]
Understand 100% that autofix is in alpha, however I thought I would add that autofix also gets confused when applying multiple changes to the same line.

Here is the repro: https://semgrep.dev/s/gordonwoodhull:wrap-strings

On semgrep.dev it produces the correct individual suggestions. However, when running on the command line with `--autofix`, it looks like it confuses the two output positions.

The rule attempts to replace the expression pattern `(String $S)` with the fix `wrap($S)`.

On input

```java
        return "a" + "b";
```

it produces the output

```
        return wrap("wrap("b") + "b";
```

**Comment by colleend** [comment]
Thanks for commenting about this issue! Would you mind filing a separate autofix issue with the contents of the comment? 🙏

**Comment by gordonwoodhull** [comment]
It’s an important issue - please don’t close.

**Comment by gordonwoodhull** [comment]
Another experience report. Solution for this and #3577 is relatively simple.

1. Remember a line offset, column offset, and active line per active file. Assume there is no overlap in matches and they are sorted by line/column.
2. If the next match is on the active line, it will need the column offset; all matches get the line offset
3. Update the offsets and active line. Four cases fall out for the formula for the column offset, depending whether pattern/fix are multiline.

I'm sorry I can't contribute a PR right away - I will get permission if this project is continued.

**Comment by ievans** [comment]
Fixed in 0.77, with tests to boot. Thanks @chair6!

**Comment by tino** [comment]
This still fails for me on 0.90.

Rules:
```yaml
rules:
- id: replace-money-with-float
  patterns:
    - pattern: |
        Money($X)
  fix: '$X'
  message: Turn obsolete Money objects into floats
  languages: [python]
  severity: WARNING
```

Code:
```python
from money import Money

works = [0, Money(1.5), Money(1.5)]
fails = [Money(1.0), Money(1.5), Money(1.5)]
```

Autofixed:
```python
from money import Money

works = [0, 1.5, 1.5]
fails = [1.0, 1.5, Money(11.5

```

Same (or worse) with 4 matches on a line.
