### ISSUE TITLE
Autofix eats up parentheses and brackets

### ISSUE THREAD

**Issue by rtpg** [semgrep/semgrep#841]
**Describe the bug**
Autofix on Python seems to sometimes eat parentheses and brackets, making code very semantically different

**To Reproduce**
https://semgrep.live/2Y0

^ this is a simple repro, where I'm trying to replace
`self.assertEquals(foo(), 1)` with `assert foo() == 1`, but I end up with `assert foo == 1`.

(I would have labelled this issue but I don't seem to have the right permissions...)

**Comment by DrewDennison** [comment]
Thanks @rtpg for the issue. We’re on it. What timeline do you like a fix? Does the end of the week work ok if it’s a minor fix?

**Comment by rtpg** [comment]
Nothing is burning of course, but if you are able to provide even a minor fix I would be able to run this across a pretty large codebase and report back on how successful the patch is.

**Comment by DrewDennison** [comment]
very cool. We'll get on it!

**Comment by rtpg** [comment]
@DrewDennison if there ends up being even a WIP branch that potentially fixes this, I'm willing to try running out to confirm that it doesn't introduce any issues. Please freel free to ping me

**Comment by aryx** [comment]
Yep, it is more difficult than expected. Hopefully we can get a fix in the next few weeks.

**Comment by dlukeomalley** [comment]
@rtpg This is fixed now for the sample provided. Mind taking a look and letting us know as you run in issues?

**Comment by rtpg** [comment]
https://semgrep.live/r650/ Based on this example, this issue is still not really fixed for brackets.


![image](https://user-images.githubusercontent.com/1408472/87517856-70636400-c6ba-11ea-97ac-96089d902a36.png)


(Basically the brackets disappear upon being replaced, does some especially nasty stuff on JSON objects)

**Comment by dlukeomalley** [comment]
@rtpg Thank you for the follow-up and excellent live example. I opened https://github.com/returntocorp/semgrep/issues/1285 to track further fixes here 🙏
