### ISSUE TITLE
pattern-regex requires pattern-inside for matches

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#912]
I found `pattern-regex` behavior confusing. It seems that it requires `pattern-inside`, and doesn't work with `pattern`. Is this expected?

`pattern` example (not working): https://semgrep.live/GdRB
`pattern-inside` example (working): https://semgrep.live/RerE

My fear is that this behavior is non-intuitive and requires too much knowledge about other Semgrep configuration.

```yaml
rules:
  - id: boto3-internal-network
    patterns:
      - pattern: boto3.client(host="...")
      - pattern-regex: '192.168\.\d{1,3}\.\d{1,3}'
    message: "Boto3 connection to internal network"
    languages: [python]
    severity: ERROR
```

**Comment by mschwager** [comment]
See also: #805 

I think it makes sense, but definitely open to hearing other thoughts. Intuitively the regex must be "inside" the other pattern. This is also consistent with other boolean composition logic in `semgrep`, e.g. if using multiple `pattern` operators with `patterns` then the whole range must match exactly. If you want the range to be inside, then you have to use `pattern-inside`.

This is consistent with other `semgrep` behavior, and deviating from that could cause even more confusion (e.g. everything in `semgrep` is consistent except for this pesky `pattern-regex` operator). But obviously if this is a burden on users we should iterate. Should we see if this causes any confusion with external users, then proceed?

**Comment by dlukeomalley** [comment]
Thank you for pointing out #805. This may be feedback on our syntax more broadly.

Originally I thought `patterns` was an "AND" clause and so expected the `pattern` and `pattern-regex` keys to both fire on that snippet of code and for there to be an overall match shown to the user. From a tech perspective I can guess why this isn't true, but it's counterintuitive to me for UX.

If we were to keep `pattern-inside`, I find it confusing because subsequent patterns aren't visibly nested within it (in the config), which breaks my expectation of our boolean composition. I don't have a visual indicator that `pattern-inside` doesn't behave like other pattern keys when ANDed together. I'd almost expect something like:

```yml
patterns:
  - pattern-inside:
    - parent: boto3.client(host="...")
    - pattern-regex: '192.168\.\d{1,3}\.\d{1,3}'
  - pattern: foobar
```

Just musings. I'll think on this more.

**Comment by dlukeomalley** [comment]
I still find this confusing. I think it's better addressed by https://github.com/returntocorp/semgrep/issues/1218 though

**Comment by aryx** [comment]
yes. Actually the new full-rule handling in semgrep-core  does not make the difference  between pattern and pattern-inside for this case and so will find the match (semgrep still does not though).
